name: Linting

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  phpcs:
    name: phpcs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set PHP version
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        coverage: none
        tools: composer:v2
    - name: Install Dependencies
      run: composer install --no-scripts
    - name: PHPCS Check
      run: ./vendor/bin/phpcs .
    # - name: PHPCS check
    #   uses: chekalsky/phpcs-action@v1
    #   with:
    #     phpcs_bin_path: './vendor/bin/phpcs ~/work/wp-astrology/wp-astrology'
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Lint assets
      run: |
        npm ci
        npm run lint

